dist: xenial
language: python
before_install: openssl version
env:
  # global:
    # - secure: AifoKzwhjV94cmcQZrdQmqRu/9rkZZvWpwBv1daeAQpLOKFPGsOm3D+x2cSw9+iCfkgDZDfqQVv1kCaFVxTll8v8jTq5SJdqEY0NmGWbj/UkNtShh609oRDsuzLxAEwtVKYjf/h8K2BRea+bl1tGkwZ2vtmYS6dxNlAijjWOfds=
    # - secure: LBSEg/gMj4u4Hrpo3zs6Y/1mTpd2RtcN49mZIFgTdbJ9IhpiNPqcEt647Lz94F9Eses2x2WbNuKqZKZZReY7QLbEzU1m0nN5jlaKrjcG5NR5clNABfFFyhgc0jBikyS4abAG8jc2efeaTrFuQwdoF4sE8YiVrkiVj2X5Xoi6sBk=
  matrix:
    - TOX_SUFFIX="requests"
    - TOX_SUFFIX="httplib2"
    - TOX_SUFFIX="boto3"
    - TOX_SUFFIX="urllib3"
    - TOX_SUFFIX="tornado4"
    - TOX_SUFFIX="aiohttp"
    - TOX_SUFFIX="httpx"
matrix:
  include:
    # Only run lint on a single 3.x
    - env: TOX_SUFFIX="lint"
      python: "3.7"
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
install:
  - pip install tox-travis codecov
  - if [[ $TOX_SUFFIX != 'lint' ]]; then python setup.py install ; fi
script:
  - tox -e "${TOX_SUFFIX}"
after_success:
  - codecov
