language: python
sudo: false
before_install: openssl version
env:
  global:
    - secure: AifoKzwhjV94cmcQZrdQmqRu/9rkZZvWpwBv1daeAQpLOKFPGsOm3D+x2cSw9+iCfkgDZDfqQVv1kCaFVxTll8v8jTq5SJdqEY0NmGWbj/UkNtShh609oRDsuzLxAEwtVKYjf/h8K2BRea+bl1tGkwZ2vtmYS6dxNlAijjWOfds=
    - secure: LBSEg/gMj4u4Hrpo3zs6Y/1mTpd2RtcN49mZIFgTdbJ9IhpiNPqcEt647Lz94F9Eses2x2WbNuKqZKZZReY7QLbEzU1m0nN5jlaKrjcG5NR5clNABfFFyhgc0jBikyS4abAG8jc2efeaTrFuQwdoF4sE8YiVrkiVj2X5Xoi6sBk=
  matrix:
    - TOX_SUFFIX="flakes"
    - TOX_SUFFIX="requests27"
    - TOX_SUFFIX="httplib2"
    - TOX_SUFFIX="boto3"
    - TOX_SUFFIX="urllib3121"
    - TOX_SUFFIX="tornado4"
    - TOX_SUFFIX="aiohttp"
matrix:
  include:
    - env: TOX_SUFFIX="flakes"
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOX_SUFFIX="requests27"
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOX_SUFFIX="httplib2"
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOX_SUFFIX="urllib3121"
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOX_SUFFIX="tornado4"
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOX_SUFFIX="aiohttp"
      python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    - env: TOX_SUFFIX="boto3"
    - env: TOX_SUFFIX="aiohttp"
      python: "pypy3.5-5.9.0"
    - env: TOX_SUFFIX="aiohttp"
      python: 3.4
  exclude:
    # Only run flakes on a single Python 2.x and a single 3.x
    - env: TOX_SUFFIX="flakes"
      python: 3.4
    - env: TOX_SUFFIX="flakes"
      python: 3.5
    - env: TOX_SUFFIX="flakes"
      python: pypy
    - env: TOX_SUFFIX="flakes"
      python: "pypy3.5-5.9.0"
    - env: TOX_SUFFIX="aiohttp"
      python: 2.7
    - env: TOX_SUFFIX="aiohttp"
      python: pypy
python:
- 2.7
- 3.4
- 3.5
- 3.6
- pypy
- "pypy3.5-5.9.0"
install:
- pip install tox-travis
- if [[ $TOX_SUFFIX != 'flakes' ]]; then python setup.py install ; fi
script:
- tox -e "${TOX_SUFFIX}"
