language: python
before_install: openssl version
env:
  - WITH_REQUESTS="2.x"
  - WITH_REQUESTS="1.x"
  - WITH_REQUESTS="False"
python:
  - 2.6
  - 2.7
install: 
  - pip install PyYAML pytest --use-mirrors
  - if [ $WITH_REQUESTS = "1.x" ] ; then pip install requests==1.2.3; fi
  - if [ $WITH_REQUESTS = "2.x" ] ; then pip install requests; fi
script:  python setup.py test
