language: python
before_install: openssl version
env:
  - WITH_REQUESTS="True"
  - WITH_REQUESTS="False"
python:
  - 2.6
  - 2.7
  - pypy
install: 
  - pip install PyYAML pytest --use-mirrors
  - if [ $WITH_REQUESTS = "True" ] ; then pip install requests; fi
script:  PYTHONPATH=`pwd` py.test --basetemp=.
